// What is javascript

/*
-> JavaScript is a dynamic computer programming language.
-> It is lightweight and most commonly used as a part of web pages, whose implementations allow client-side script to interact with the user and make dynamic pages. It is an interpreted programming language with object-oriented capabilities.
-> JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.Complementary to and integrated with HTML.Open and cross-platform
*/

/****   JavaScript Values   ****/
//  -> The JavaScript syntax defines two types of values

/*
    -> Fixed values are called Literals.
    -> Variable values are called Variables.
 */

/**** Using console in javascript ****/

/**** var variable type / box variable name / = assignement / 60 assiged values ****/

// javascript language case-sensitive 

/**************** variable useing var() in javascript *************************/

{
    // var box = "LiveScript"
    // console.log(box)

    // var Names="foo";
    // var names="Javascript";
    // console.log(Names);

    // var number1 = 15;
    // var number2 = 2;
    // console.log(number1 ** number2);
    // var box1="toys";
    // var box1="cloths";
    // var box1 = 45;
   // console.log(box1)
}


// box1 = "apple"
// box1 = 45
// console.log(box1);

/*******New Html Element Add In Though Javascript *********/

{
    // var newelement = document.createElement("h1");
    // newelement.textContent="hello world";
    // document.body.appendChild(newelement);

    // var newelement = document.createElement("marquee" , Option);
    // newelement.textContent="hello world";
    // document.body.appendChild(newelement);

    // var newelement=document.createElement("pre");
    // newelement.textContent="how are you!";
    // document.body.appendChild(newelement);
}

// document.write('hello javascript!');


// js comments

// single-line comments

/* multi-line 
comments */


// Template literals

{
    var _nameone = "5";
    var name20 = '5';

    console.log(name20);

    console.log(typeof(_nameone))

}


{
    // alert("_nameone + ${name20}")
    // alert(`${_nameone} + ${name20}`); 
}

// Rules for Naming In JavaScript Variables

{
    //valid
    // let a = 'hello';
    // let _a = 'hello';
    // let $a = 'hello';
}
{
    //invalid
    // Let 1a = 'hello'; // this gives an error
}

// JavaScript is case-sensitive. So y and Y are different variables

{
    // let y = "hi";
    // let Y = 5;

    // console.log(y);
    // console.log(Y); 
}

// Keywords cannot be used as variable names.

{
    //invalid
    // let new = 5; // Error! new is a keyword.
}

/*  

Name must start with a letter (a to z or A to Z), underscore( _ ), or dollar( $ ) sign. After first letter we can use digits (0 to 9), for example value1. JavaScript variables are case sensitive, for example x and X are different variables.

*/